### PR TITLE
Added complex feature implementation

### PR DESCRIPTION
**Pull request by malcolmgreaves**

### CODE REVIEW

**Comment by malcolmgreaves** [comment]
This might be a little tricky since Katie updated working...

**Comment by krivard** [comment]
I haven't looked at the whole merge yet; going to post questions here as I go.

It looks like Configuration has a new flag, but doesn't actually add a command line argument or set any new configuration variables. Neither does ExperimentConfiguration. How does the complexfeature config file path get into the system?

**Comment by malcolmgreaves** [comment]
I tested this in QueryAnswer using QueryAnswererConfiguration:

  QueryAnswererConfiguration c = new QueryAnswererConfiguration(
                args,
                Configuration.USE_DEFAULTS | Configuration.USE_QUERIES | Configuration.USE_OUTPUT |
                Configuration.USE_PARAMS | Configuration.USE_COMPLEX_FEATURES);

Question: is it a good idea to add this to something more "base" i.e. Configuration?

**Comment by krivard** [comment]
Okay, I can see that you're doing

```
        ComplexFeatureLibrary.init(program, c.complexFeatureConfigFile);
```

...but where are you setting `c.complexFeatureConfigFile`? Isn't it still `null`?

In general, if only one executable is going to be using something, we add it to a custom configFile (as in QueryAnswerer, with the QueryAnswerer-specific settings). If more than one will use it, we add it to Configuration or ExperimentConfiguration, whichever is more appropriate.

**Comment by krivard** [comment]
OK, these changes are merged -- but I'm not convinced complexFeature is working yet :(

**Comment by malcolmgreaves** [comment]
Ok. At the moment, that's the only place where I use it.
- Malcolm

**Comment by malcolmgreaves** [comment]
It works. The file is set by the complex feature config option.
- Malcolm

**Comment by malcolmgreaves** [comment]
Ok so I have to eat my words here (gosh, again!) I didn't merge properly. I lost the code that adds the config file option. It's supposed to be in Configuration. I can edit it and put up another PR soon (once I get back to campus).

**Comment by krivard** [comment]
Cool :)

**Pull request merged**
